# Generated by Django 2.2.2 on 2019-06-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = {
        migrations.RemoveField(
            model_name='product',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_name',
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='NOTHING', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default='2019-10-15'),
        ),
    }
