# Generated by Django 2.2.2 on 2019-06-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190614_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
