# Generated by Django 2.2.2 on 2019-06-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190614_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default='2019-10-15'),
        ),
    ]
